version: '3.5'


networks:
  develop:
    ipam:
      config:
      - subnet: 172.16.1.0/24

services:
  mysql57:
    image: ${IMAGE_BASE}/mysql:5.7.41
    container_name: mysql57
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWD_57:-123456}
    ports:
      - ${MYSQL_PORT_57:-3306}:3306
    volumes:
      - ./mysql/5.7/data:/var/lib/mysql
      - ./logs/mysql/5.7:/var/log/mysql
    command: 
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode=
      --default-time-zone=+8:00
      --lower-case-table-names=1
    networks:
      develop:
        ipv4_address: 172.16.1.9

  elasticsearch:
    image: ${IMAGE_BASE}/elasticsearch:${ELK_VERSION:-7.17.7}
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=cc-docker-cluster
      - node.name=cc-docker-node
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      # - xpack.security.transport.ssl.enabled=false
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      # - discovery.seed_hosts=
      # - cluster.initial_master_nodes=cc-docker-node
      - discovery.type=single-node
    volumes:
      - "./elasticsearch/data/${ELK_VERSION:-7.17.7}:/usr/share/elasticsearch/data:rw"
      - "./elasticsearch/plugins/${ELK_VERSION:-7.17.7}:/usr/share/elasticsearch/plugins"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
        develop:
          ipv4_address: 172.16.1.10
    depends_on:
      - redis

  kibana:
    image: ${IMAGE_BASE}/kibana:${ELK_VERSION:-7.17.7}
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
    networks:
        develop:
          ipv4_address: 172.16.1.11
    depends_on:
      - elasticsearch

  openresty:
    image: ${IMAGE_BASE}/openresty:1.21.4.1
    container_name: openresty
    restart: always
    ports:
      - 80:80
    volumes:
      - "${WWWROOT_PATH}:/data/wwwroot"
      - "./logs/wwwlogs:/data/wwwlogs"
      - "./logs/nginx:/usr/local/openresty/nginx/logs"
      - "./openresty/config/conf:/usr/local/openresty/nginx/conf"
      - "./openresty/config/vhost:/usr/local/openresty/nginx/conf/vhost"
      - "./openresty/config/rewrite:/usr/local/openresty/nginx/conf/rewrite"
    networks:
        develop:
          ipv4_address: 172.16.1.2
    depends_on:
      - php73
      - php81
      - php82

  redis:
    image: ${IMAGE_BASE}/redis:7.0.7
    container_name: redis
    restart: always
    volumes:
      - "./redis/redis.conf:/etc/redis/redis.conf"
      - "./redis/data:/data/db"
      - "./logs/redis:/data/logs"
    command: ["redis-server","/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    networks:
        develop:
          ipv4_address: 172.16.1.3
    depends_on:
      - mysql57
  php73:
    image: ${IMAGE_BASE}/php:7.3
    container_name: php73
    restart: always
    volumes:
      - "${WWWROOT_PATH}:/data/wwwroot:rw"
      - "./php/php73/etc:/usr/local/etc"
    working_dir: /data/wwwroot/
    #privileged: true
    networks:
        develop:
          ipv4_address: 172.16.1.73
    depends_on:
      - elasticsearch
      - redis
  php81:
    image: ${IMAGE_BASE}/php:8.1
    container_name: php81
    restart: always
    volumes:
      - "${WWWROOT_PATH}:/data/wwwroot"
      - "./php/php81/etc:/usr/local/etc"
    working_dir: /data/wwwroot/
    networks:
        develop:
          ipv4_address: 172.16.1.81
    depends_on:
      - elasticsearch
      - redis
  php82:
    image: ${IMAGE_BASE}/php:8.2
    container_name: php82
    restart: always
    volumes:
      - "${WWWROOT_PATH}:/data/wwwroot"
      - "./php/php82/etc:/usr/local/etc"
    working_dir: /data/wwwroot/
    networks:
        develop:
          ipv4_address: 172.16.1.82
    depends_on:
      - elasticsearch
      - redis
