ARG ELK_VER
FROM elasticsearch:${ELK_VER}
LABEL author="0x49"
LABEL email="1458513@qq.com"
EXPOSE 9200


# PASSWORD apm_system = zBLcav89S41j8uxrISKa
# PASSWORD kibana_system = MbixEUH566YqCfuvu0Bq
# PASSWORD kibana = MbixEUH566YqCfuvu0Bq
# PASSWORD logstash_system = nh3swmjv0gKRqFR7AnJA
# PASSWORD beats_system = LmtponekGb21GOxWH3A1
# PASSWORD remote_monitoring_user = Q8FiXq2J6teC4SJS1OEN
# PASSWORD elastic = aSzC94GW8AaDwBy1D4EM